[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_FMP_API_KEY = "your-api-key-here"
  NEXT_PUBLIC_SUPABASE_URL = "your_supabase_url_here"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"